version: "3"
services:

  api:
    restart: unless-stopped
    build: ./server
    volumes: 
      - ./server:/usr/src/app
    working_dir: /usr/src/app
    command: npm run start
    ports:
      - "3300:3300"

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: app
    volumes:
      - ./server/data:/data/db
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password

  app:
    restart: unless-stopped
    build: .
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: yarn start
    ports:
      - 3000:3000